# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13tladumtAKvMiE8d_Gebt4UvsQT9-g66
"""

import pandas as pd

df=pd.read_csv("B3DB_classification.csv",sep='\t')

df.head(10)

df=df[['SMILES','BBB+/BBB-']]

df.head()

df['label']=df['BBB+/BBB-'].map({'BBB+':1,'BBB-':0})

df.head()

df['BBB+/BBB-'].value_counts()

df['SMILES'].isnull().sum()

df['label'].isnull().sum()

df=df.drop(columns=['BBB+/BBB-'])

df.head()

from sklearn.utils.class_weight import compute_class_weight
import numpy as np
import torch

class_weights=compute_class_weight(
    class_weight='balanced',
    classes=np.array([0,1]),
    y=df['label']
)

class_weights=torch.tensor(class_weights,dtype=torch.float)
print(class_weights)

from sklearn.model_selection import train_test_split

X=df['SMILES']
y=df['label']
print(X.dtype)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

df=pd.DataFrame(X_train,y_train)





from transformers import AutoTokenizer

tokenizer=AutoTokenizer.from_pretrained("DeepChem/ChemBERTa-10M-MTR")

train_tokens=tokenizer(
    list(X_train),
    padding=True,
    truncation=True,
    max_length=256,
    return_tensors='pt'
)

test_tokens=tokenizer(
    list(X_test),
    padding=True,
    truncation=True,
    max_length=256,
    return_tensors='pt'
)

from torch.utils.data import Dataset

class BBBDataset(Dataset):
    def __init__(self,encodings,labels):
        self.encodings=encodings
        self.labels=labels.values


    def __len__(self):
        return len(self.labels)

    def __getitem__(self,idx):
        item={key:val[idx] for key,val in self.encodings.items()}
        item['labels']=torch.tensor(self.labels[idx])
        return item

train_dataset=BBBDataset(train_tokens,y_train)
test_dataset=BBBDataset(test_tokens,y_test)

from torch.utils.data import DataLoader

train_loader=DataLoader(train_dataset,batch_size=16,shuffle=True)
test_loader=DataLoader(test_dataset,batch_size=16)

from transformers import Trainer

class WeightedTrainer(Trainer):
    def compute_loss(self,model,inputs,return_outputs=False, **kwargs):
        labels=inputs.pop('labels')
        outputs=model(**inputs)
        logits=outputs.get("logits")
        loss_fct=torch.nn.CrossEntropyLoss(weight=class_weights.to(model.device))
        loss=loss_fct(logits,labels)
        return (loss,outputs) if return_outputs else loss

from transformers import Trainer,TrainingArguments

from transformers import AutoModelForSequenceClassification

model=AutoModelForSequenceClassification.from_pretrained(
    "DeepChem/ChemBERTa-10M-MTR",
    num_labels=2
)



import mlflow
mlflow.set_tracking_uri("file:///content/mlruns")
mlflow.set_experiment("BBB Classification ")

training_args=TrainingArguments(
    output_dir="./results",
    learning_rate=1e-5,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=5,
    eval_strategy="epoch",
    logging_dir="./logs",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model='eval_roc_auc',
    fp16=True,
)

from sklearn.metrics import accuracy_score,f1_score,roc_auc_score

def compute_metrics(eval_pred):
    logits,labels=eval_pred
    preds=logits.argmax(axis=1)

    return{"accuracy":accuracy_score(labels,preds),
            "f1":f1_score(labels,preds),
           "roc_auc":roc_auc_score(labels,preds)
          }

trainer=WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

with mlflow.start_run():
  trainer.train()
  results=trainer.evaluate()

  mlflow.log_metrics({
      "accuracy":results["eval_accuracy"],
      "f1":results["eval_f1"],
      "roc_auc":results["eval_roc_auc"],
      "eval_loss":results["eval_loss"]
  })

  mlflow.log_params({
      "learning_rate":training_args.learning_rate,
      "batch_size":training_args.per_device_train_batch_size,
      "eval batc":training_args.per_device_eval_batch_size,
      "num_epochs":training_args.num_train_epochs
  })

print(mlflow.get_tracking_uri())


from peft import LoraConfig,get_peft_model,TaskType

lora_config=LoraConfig(

    r=16,
    lora_alpha=32,
    target_modules=["query","value"],
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.SEQ_CLS
)
model=get_peft_model(model,lora_config)



trainer=WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

